"""GitHub Models embeddings utilities for NaviRag Trading."""

import argparse
import json
import os
from pathlib import Path
from typing import Any

import requests
from dotenv import load_dotenv

from src.config import DATA_PROCESSED_DIR
from src.utils.mongodb import MongoDBClient

CHUNKS_FILE = DATA_PROCESSED_DIR / "chunks.json"
DEFAULT_GITHUB_EMBEDDING_MODEL = "openai/text-embedding-3-small"
DEFAULT_GITHUB_EMBEDDINGS_ENDPOINT = "https://models.github.ai/inference/embeddings"
BATCH_SIZE = 20


class EmbeddingClient:
    """GitHub Models embeddings client."""

    def __init__(
        self,
        api_key: str | None = None,
        model: str | None = None,
        endpoint: str | None = None,
    ) -> None:
        load_dotenv()
        self.api_key = api_key or os.getenv("GITHUB_TOKEN")
        if not self.api_key:
            raise RuntimeError("Falta GITHUB_TOKEN en el entorno. Configura .env.")

        self.model = (
            model
            or os.getenv("GITHUB_EMBEDDING_MODEL")
            or DEFAULT_GITHUB_EMBEDDING_MODEL
        )
        self.endpoint = (
            endpoint
            or os.getenv("GITHUB_MODELS_EMBEDDINGS_ENDPOINT")
            or DEFAULT_GITHUB_EMBEDDINGS_ENDPOINT
        )

    def get_embedding(self, text: str) -> list[float]:
        """Return one embedding vector for a text."""
        return self.get_embeddings([text])[0]

    def get_embeddings(self, texts: list[str]) -> list[list[float]]:
        """Return embedding vectors for a batch of texts."""
        response = requests.post(
            self.endpoint,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": self.model,
                "input": texts,
            },
            timeout=60,
        )

        if not response.ok:
            raise RuntimeError(
                f"Error en GitHub Models embeddings: HTTP {response.status_code} - "
                f"{response.text[:300]}"
            )

        payload = response.json()
        return [item["embedding"] for item in payload.get("data", [])]


def load_chunks(input_file: Path = CHUNKS_FILE) -> list[dict]:
    """Load traceable chunks generated by the chunking step."""
    if not input_file.exists():
        raise FileNotFoundError(
            f"No existe {input_file}. Ejecuta primero: python -m src.ingesta.chunking"
        )

    payload = json.loads(input_file.read_text(encoding="utf-8"))
    return payload.get("chunks", [])


def build_embedding_records_for_batch(
    chunks: list[dict],
    embedder: EmbeddingClient,
) -> list[dict]:
    """Generate embedding records for one batch of chunks."""
    records = []
    texts = [chunk.get("text", "") for chunk in chunks]
    embeddings = embedder.get_embeddings(texts)

    for chunk, embedding in zip(chunks, embeddings, strict=True):
        records.append(
            {
                "chunk_id": chunk.get("chunk_id"),
                "file": chunk.get("file"),
                "page": chunk.get("page"),
                "section": chunk.get("section"),
                "page_chunk_index": chunk.get("page_chunk_index"),
                "text": chunk.get("text"),
                "character_count": chunk.get("character_count"),
                "embedding": embedding,
                "embedding_model": embedder.model,
            }
        )

    return records


def save_embeddings_to_mongodb(records: list[dict]) -> int:
    """Persist embedding records into MongoDB Atlas."""
    return MongoDBClient().upsert_embedding_records(records)


def select_pending_chunks(
    chunks: list[dict],
    existing_records: list[dict],
    limit: int | None = None,
) -> list[dict]:
    """Select chunks that do not have embeddings yet."""
    embedded_ids = {record.get("chunk_id") for record in existing_records}
    pending_chunks = [
        chunk for chunk in chunks if chunk.get("chunk_id") not in embedded_ids
    ]
    if limit is not None:
        pending_chunks = pending_chunks[:limit]
    return pending_chunks


def generate_embeddings(
    limit: int | None = None,
    rebuild_mongodb: bool = False,
) -> list[dict]:
    """Generate embeddings and store them in MongoDB Atlas."""
    if rebuild_mongodb and limit is not None:
        raise ValueError("No combines --rebuild-mongodb con --limit.")

    chunks = load_chunks()
    embedder = EmbeddingClient()
    mongo_client = MongoDBClient()

    if rebuild_mongodb:
        deleted_count = mongo_client.delete_all_documents()
        print(f"Rebuild MongoDB: documentos eliminados antes de reindexar: {deleted_count}")
    else:
        print(
            "Advertencia: se hara upsert incremental sobre la coleccion MongoDB "
            "existente. Tras cambios de ingesta/chunking, usa --rebuild-mongodb "
            "para reindexar desde cero y evitar mezclar embeddings viejos y nuevos."
        )

    records = []
    pending_chunks = select_pending_chunks(
        chunks=chunks,
        existing_records=records,
        limit=limit,
    )

    for start in range(0, len(pending_chunks), BATCH_SIZE):
        batch = pending_chunks[start : start + BATCH_SIZE]
        new_records = build_embedding_records_for_batch(
            chunks=batch,
            embedder=embedder,
        )
        records.extend(new_records)
        mongo_client.upsert_embedding_records(new_records)
        print(f"Lote guardado. Total acumulado: {len(records)}")

    return records


def parse_args() -> Any:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Genera embeddings de chunks locales.")
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Cantidad maxima de chunks nuevos a procesar en esta ejecucion.",
    )
    parser.add_argument(
        "--rebuild-mongodb",
        action="store_true",
        help=(
            "Borra primero todos los documentos de la coleccion MongoDB configurada "
            "y regenera embeddings para todos los chunks locales. No combinar con --limit."
        ),
    )
    return parser.parse_args()


def main() -> None:
    """Run embeddings generation from the command line."""
    args = parse_args()
    records = generate_embeddings(
        limit=args.limit,
        rebuild_mongodb=args.rebuild_mongodb,
    )
    print(f"Embeddings enviados a MongoDB: {len(records)}")


if __name__ == "__main__":
    main()
