"""Simple GitHub Models embeddings generation for NaviRag Trading."""

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import requests
from dotenv import load_dotenv

from src.config import DATA_PROCESSED_DIR, VECTORSTORE_DIR

CHUNKS_FILE = DATA_PROCESSED_DIR / "chunks.json"
EMBEDDINGS_OUTPUT_FILE = VECTORSTORE_DIR / "embeddings.json"
DEFAULT_EMBEDDING_MODEL = "openai/text-embedding-3-small"
DEFAULT_GITHUB_MODELS_ENDPOINT = "https://models.github.ai/inference/embeddings"
BATCH_SIZE = 20


def load_chunks(input_file: Path = CHUNKS_FILE) -> list[dict]:
    """Load traceable chunks generated by the chunking step."""
    if not input_file.exists():
        raise FileNotFoundError(
            f"No existe {input_file}. Ejecuta primero: python -m src.chunking"
        )

    payload = json.loads(input_file.read_text(encoding="utf-8"))
    return payload.get("chunks", [])


def load_embedding_config() -> dict:
    """Load GitHub Models configuration without exposing credentials."""
    load_dotenv()
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("Falta GITHUB_TOKEN en el entorno. Configura .env.")

    return {
        "token": token,
        "endpoint": os.getenv(
            "GITHUB_MODELS_ENDPOINT",
            DEFAULT_GITHUB_MODELS_ENDPOINT,
        ),
        "model": os.getenv("EMBEDDING_MODEL", DEFAULT_EMBEDDING_MODEL),
    }


def request_embeddings(
    texts: list[str],
    token: str,
    endpoint: str,
    model: str,
) -> list[list[float]]:
    """Request embeddings from GitHub Models REST API."""
    response = requests.post(
        endpoint,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        json={
            "model": model,
            "input": texts,
        },
        timeout=60,
    )

    if not response.ok:
        raise RuntimeError(
            f"Error en GitHub Models: HTTP {response.status_code} - "
            f"{response.text[:300]}"
        )

    payload = response.json()
    return [item["embedding"] for item in payload.get("data", [])]


def build_embedding_records(
    chunks: list[dict],
    token: str,
    endpoint: str,
    model: str,
    batch_size: int = BATCH_SIZE,
) -> list[dict]:
    """Generate embeddings and preserve chunk traceability."""
    records = []

    for start in range(0, len(chunks), batch_size):
        batch = chunks[start : start + batch_size]
        texts = [chunk.get("text", "") for chunk in batch]
        embeddings = request_embeddings(
            texts=texts,
            token=token,
            endpoint=endpoint,
            model=model,
        )

        for chunk, embedding in zip(batch, embeddings, strict=True):
            records.append(
                {
                    "chunk_id": chunk.get("chunk_id"),
                    "file": chunk.get("file"),
                    "page": chunk.get("page"),
                    "page_chunk_index": chunk.get("page_chunk_index"),
                    "text": chunk.get("text"),
                    "character_count": chunk.get("character_count"),
                    "embedding": embedding,
                    "embedding_model": model,
                }
            )

    return records


def save_embeddings(
    records: list[dict],
    model: str,
    output_file: Path = EMBEDDINGS_OUTPUT_FILE,
) -> None:
    """Save embeddings to the local vectorstore folder."""
    output_file.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "system": "NaviRag Trading",
        "description": "Embeddings locales generados desde chunks trazables.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_file": str(CHUNKS_FILE),
        "embedding_model": model,
        "total_embeddings": len(records),
        "embeddings": records,
    }
    output_file.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def generate_embeddings(limit: int | None = None) -> list[dict]:
    """Generate embeddings for all chunks or for a limited test sample."""
    chunks = load_chunks()
    if limit is not None:
        chunks = chunks[:limit]

    config = load_embedding_config()
    records = build_embedding_records(
        chunks=chunks,
        token=config["token"],
        endpoint=config["endpoint"],
        model=config["model"],
    )
    save_embeddings(records=records, model=config["model"])
    return records


def parse_args() -> Any:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Genera embeddings de chunks locales.")
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Cantidad maxima de chunks a procesar para pruebas.",
    )
    return parser.parse_args()


def main() -> None:
    """Run embeddings generation from the command line."""
    args = parse_args()
    records = generate_embeddings(limit=args.limit)
    print(f"Embeddings generados: {len(records)}")
    print(f"Salida: {EMBEDDINGS_OUTPUT_FILE}")


if __name__ == "__main__":
    main()
